/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Bryan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    private Controller controller;
    
    public TelaPrincipal() {
        initComponents();
        controller = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAtributos = new javax.swing.JPanel();
        painelValores = new javax.swing.JPanel();
        txtFor = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextField();
        txtCon = new javax.swing.JTextField();
        txtInt = new javax.swing.JTextField();
        txtSab = new javax.swing.JTextField();
        txtCar = new javax.swing.JTextField();
        painelNomes = new javax.swing.JPanel();
        labelFor = new javax.swing.JLabel();
        labelDes = new javax.swing.JLabel();
        labelCon = new javax.swing.JLabel();
        labelInt = new javax.swing.JLabel();
        labelSab = new javax.swing.JLabel();
        labelCar = new javax.swing.JLabel();
        painelModificadores = new javax.swing.JPanel();
        lblModFor = new javax.swing.JLabel();
        lblModDes = new javax.swing.JLabel();
        lblModCon = new javax.swing.JLabel();
        lblModInt = new javax.swing.JLabel();
        lblModSab = new javax.swing.JLabel();
        lblModCar = new javax.swing.JLabel();
        painelCaracteristicas = new javax.swing.JPanel();
        painelPv = new javax.swing.JPanel();
        labelDados = new javax.swing.JLabel();
        txtDados = new javax.swing.JTextField();
        labelMais = new javax.swing.JLabel();
        txtModVida = new javax.swing.JTextField();
        labelVidaTotal = new javax.swing.JLabel();
        labelPMs = new javax.swing.JLabel();
        painelTipoNivel = new javax.swing.JPanel();
        cbTipoCriatura = new javax.swing.JComboBox<>();
        labelNivel = new javax.swing.JLabel();
        painelNome = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelLegenda = new javax.swing.JLabel();
        labelForca = new javax.swing.JLabel();
        labelForPericia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelDesPericia = new javax.swing.JLabel();
        labelConPericia = new javax.swing.JLabel();
        labelIntPericia = new javax.swing.JLabel();
        labelSabPericia = new javax.swing.JLabel();
        labelCarPericia = new javax.swing.JLabel();
        btnTransformar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        painelAtributos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Atributos"));

        painelValores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valores"));

        txtFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFor.setText("10");
        txtFor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtForFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtForFocusLost(evt);
            }
        });
        txtFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForActionPerformed(evt);
            }
        });

        txtDes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDes.setText("10");
        txtDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDesFocusLost(evt);
            }
        });

        txtCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCon.setText("10");
        txtCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConFocusLost(evt);
            }
        });

        txtInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInt.setText("10");
        txtInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIntFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIntFocusLost(evt);
            }
        });

        txtSab.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSab.setText("10");
        txtSab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSabFocusLost(evt);
            }
        });

        txtCar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCar.setText("10");
        txtCar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelValoresLayout = new javax.swing.GroupLayout(painelValores);
        painelValores.setLayout(painelValoresLayout);
        painelValoresLayout.setHorizontalGroup(
            painelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtCon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInt)
                    .addComponent(txtSab)
                    .addComponent(txtCar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelValoresLayout.setVerticalGroup(
            painelValoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelValoresLayout.createSequentialGroup()
                .addComponent(txtFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelNomes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Atr"));
        painelNomes.setMinimumSize(new java.awt.Dimension(100, 200));
        painelNomes.setPreferredSize(new java.awt.Dimension(56, 150));

        labelFor.setText("FOR:");

        labelDes.setText("DES:");

        labelCon.setText("CON:");

        labelInt.setText("INT:");

        labelSab.setText("SAB:");
        labelSab.setPreferredSize(new java.awt.Dimension(23, 19));

        labelCar.setText("CAR:");
        labelCar.setPreferredSize(new java.awt.Dimension(25, 19));

        javax.swing.GroupLayout painelNomesLayout = new javax.swing.GroupLayout(painelNomes);
        painelNomes.setLayout(painelNomesLayout);
        painelNomesLayout.setHorizontalGroup(
            painelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDes)
                    .addComponent(labelCon)
                    .addComponent(labelFor)
                    .addComponent(labelCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSab, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelNomesLayout.setVerticalGroup(
            painelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomesLayout.createSequentialGroup()
                .addComponent(labelFor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelDes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSab, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelModificadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Modificadores"));

        lblModFor.setText("+0");

        lblModDes.setText("+0");

        lblModCon.setText("+0");

        lblModInt.setText("+0");

        lblModSab.setText("+0");

        lblModCar.setText("+0");

        javax.swing.GroupLayout painelModificadoresLayout = new javax.swing.GroupLayout(painelModificadores);
        painelModificadores.setLayout(painelModificadoresLayout);
        painelModificadoresLayout.setHorizontalGroup(
            painelModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModificadoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(painelModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblModSab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModDes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblModCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        painelModificadoresLayout.setVerticalGroup(
            painelModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelModificadoresLayout.createSequentialGroup()
                .addComponent(lblModFor)
                .addGap(18, 18, 18)
                .addComponent(lblModDes)
                .addGap(18, 18, 18)
                .addComponent(lblModCon)
                .addGap(18, 18, 18)
                .addComponent(lblModInt)
                .addGap(18, 18, 18)
                .addComponent(lblModSab)
                .addGap(18, 18, 18)
                .addComponent(lblModCar)
                .addContainerGap())
        );

        javax.swing.GroupLayout painelAtributosLayout = new javax.swing.GroupLayout(painelAtributos);
        painelAtributos.setLayout(painelAtributosLayout);
        painelAtributosLayout.setHorizontalGroup(
            painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelValores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelModificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAtributosLayout.setVerticalGroup(
            painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtributosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtributosLayout.createSequentialGroup()
                        .addGroup(painelAtributosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelModificadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelNomes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelCaracteristicas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Características"));

        painelPv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), " PVs e PMs"));

        labelDados.setText("Dados:");

        txtDados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDados.setText("12d8");
        txtDados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDadosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDadosFocusLost(evt);
            }
        });

        labelMais.setText("+");

        txtModVida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModVida.setText("45");
        txtModVida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtModVidaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtModVidaFocusLost(evt);
            }
        });

        labelVidaTotal.setText("Vida Total:  100");

        labelPMs.setText("PMs:   5");

        javax.swing.GroupLayout painelPvLayout = new javax.swing.GroupLayout(painelPv);
        painelPv.setLayout(painelPvLayout);
        painelPvLayout.setHorizontalGroup(
            painelPvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelVidaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPvLayout.createSequentialGroup()
                        .addComponent(labelPMs, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelPvLayout.createSequentialGroup()
                        .addComponent(labelDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDados, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtModVida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        painelPvLayout.setVerticalGroup(
            painelPvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPvLayout.createSequentialGroup()
                .addGroup(painelPvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDados)
                    .addComponent(txtDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMais)
                    .addComponent(txtModVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelVidaTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPMs)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelTipoNivel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tipo e nível"));

        cbTipoCriatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Animais", "Constructos", "Espíritos", "Humanoides", " Monstros", " Mortos-Vivos" }));

        labelNivel.setText("Nível: 5");

        javax.swing.GroupLayout painelTipoNivelLayout = new javax.swing.GroupLayout(painelTipoNivel);
        painelTipoNivel.setLayout(painelTipoNivelLayout);
        painelTipoNivelLayout.setHorizontalGroup(
            painelTipoNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoNivelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTipoNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTipoCriatura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        painelTipoNivelLayout.setVerticalGroup(
            painelTipoNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTipoNivelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTipoCriatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(labelNivel)
                .addContainerGap())
        );

        painelNome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome:"));

        javax.swing.GroupLayout painelNomeLayout = new javax.swing.GroupLayout(painelNome);
        painelNome.setLayout(painelNomeLayout);
        painelNomeLayout.setHorizontalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNome)
                .addContainerGap())
        );
        painelNomeLayout.setVerticalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeLayout.createSequentialGroup()
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCaracteristicasLayout = new javax.swing.GroupLayout(painelCaracteristicas);
        painelCaracteristicas.setLayout(painelCaracteristicasLayout);
        painelCaracteristicasLayout.setHorizontalGroup(
            painelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCaracteristicasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelCaracteristicasLayout.createSequentialGroup()
                        .addComponent(painelPv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(painelTipoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelCaracteristicasLayout.setVerticalGroup(
            painelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCaracteristicasLayout.createSequentialGroup()
                .addComponent(painelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(painelCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelTipoNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelPv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Perícias"));

        labelLegenda.setText("Baseadas em:  |  Trei / Não Trei");

        labelForca.setText("Força:");

        labelForPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelForPericia.setText("+0 / +0 ");

        jLabel1.setText("Destreza:");

        jLabel2.setText("Constituição:");

        jLabel3.setText("Inteligência:");

        jLabel4.setText("Sabedoria:");

        jLabel5.setText("Carisma:");

        labelDesPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDesPericia.setText("+0 / +0");

        labelConPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConPericia.setText("+0 / +0");

        labelIntPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIntPericia.setText("+0 / +0");

        labelSabPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSabPericia.setText("+0 / +0");

        labelCarPericia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCarPericia.setText("+0 / +0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(labelForca)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelForPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDesPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelConPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelIntPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSabPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCarPericia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLegenda)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLegenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForca)
                    .addComponent(labelForPericia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelDesPericia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelConPericia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelIntPericia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelSabPericia))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelCarPericia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnTransformar.setText("Transformar");
        btnTransformar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransformarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCaracteristicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTransformar)
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnTransformar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtForActionPerformed

    private void btnTransformarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransformarActionPerformed
        
        try{
            String con =                txtCon.getText();
            String forca =              txtFor.getText();
            String des =                txtDes.getText();
            String intel =              txtInt.getText();
            String sab =                txtSab.getText();
            String car =                txtCar.getText();
            String dados =              txtDados.getText();
            String modificadorVida =    txtModVida.getText();
            int tipo =                  cbTipoCriatura.getSelectedIndex();

            controller.transformar(con, forca, des, intel, sab, car, tipo, dados, modificadorVida);
        } catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Os valores devem ser apenas números, não colocar letras");
        } catch(java.lang.ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Os dados de vida estão errados, insira valores como \"2d6\" ou \"10d8\"");
        }
        
        //mudar os labels, esse são os mais diretos
        labelVidaTotal.setText("Vida Total: " + controller.obterVida());
        labelPMs.setText("PMs: " + controller.obterPm());
        labelNivel.setText("Nível: " + controller.obterNivel());
        
        //para os modificadores e pericias é necessário um vetor e uma matriz
        int[] modificadores = controller.obterAtributos();
        int[][] pericias = controller.obterPericias();

        lblModFor.setText(modificadores[0] + "");
        lblModDes.setText(modificadores[1] + "");
        lblModCon.setText(modificadores[2] + "");
        lblModInt.setText(modificadores[3] + "");
        lblModSab.setText(modificadores[4] + "");
        lblModCar.setText(modificadores[5] + "");
        
        labelForPericia.setText(pericias[0][0] + " / " + pericias[0][1] );
        labelDesPericia.setText(pericias[1][0] + " / " + pericias[1][1] );
        labelConPericia.setText(pericias[2][0] + " / " + pericias[2][1] );
        labelIntPericia.setText(pericias[3][0] + " / " + pericias[3][1] );
        labelSabPericia.setText(pericias[4][0] + " / " + pericias[4][1] );
        labelCarPericia.setText(pericias[5][0] + " / " + pericias[5][1] );
    }//GEN-LAST:event_btnTransformarActionPerformed
    
    //------------Métodos para selecionar ao focar nos campos------------\\
    private void txtForFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForFocusGained
        txtFor.selectAll();
    }//GEN-LAST:event_txtForFocusGained

    private void txtDesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDesFocusGained
        txtDes.selectAll();
    }//GEN-LAST:event_txtDesFocusGained

    private void txtConFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConFocusGained
        txtCon.selectAll();
    }//GEN-LAST:event_txtConFocusGained

    private void txtIntFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntFocusGained
        txtInt.selectAll();
    }//GEN-LAST:event_txtIntFocusGained

    private void txtSabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSabFocusGained
        txtSab.selectAll();
    }//GEN-LAST:event_txtSabFocusGained

    private void txtCarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarFocusGained
        txtCar.selectAll();
    }//GEN-LAST:event_txtCarFocusGained

    private void txtDadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDadosFocusGained
        txtDados.selectAll();
    }//GEN-LAST:event_txtDadosFocusGained

    private void txtModVidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModVidaFocusGained
        txtModVida.selectAll();
    }//GEN-LAST:event_txtModVidaFocusGained

    //------------Métodos para evitar campos vazios------------\\
    private void txtDadosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDadosFocusLost
        if (txtDados.getText().trim().equals("")) txtDados.setText("2d8");
    }//GEN-LAST:event_txtDadosFocusLost

    private void txtModVidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtModVidaFocusLost
        if (txtModVida.getText().trim().equals("")) txtModVida.setText("5");
    }//GEN-LAST:event_txtModVidaFocusLost

    private void txtForFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForFocusLost
        if (txtFor.getText().trim().equals("")) txtFor.setText("10");
    }//GEN-LAST:event_txtForFocusLost

    private void txtDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDesFocusLost
        if (txtDes.getText().trim().equals("")) txtDes.setText("10");
    }//GEN-LAST:event_txtDesFocusLost

    private void txtConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConFocusLost
        if (txtCon.getText().trim().equals("")) txtCon.setText("10");
    }//GEN-LAST:event_txtConFocusLost

    private void txtIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIntFocusLost
        if (txtInt.getText().trim().equals("")) txtInt.setText("10");
    }//GEN-LAST:event_txtIntFocusLost

    private void txtSabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSabFocusLost
        if (txtSab.getText().trim().equals("")) txtSab.setText("10");
    }//GEN-LAST:event_txtSabFocusLost

    private void txtCarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCarFocusLost
        if (txtCar.getText().trim().equals("")) txtCar.setText("10");
    }//GEN-LAST:event_txtCarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for ( LookAndFeelInfo info : UIManager.getInstalledLookAndFeels() ) {
                if ("Windows".equals( info.getName() ) ) {
                    UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
            } catch ( UnsupportedLookAndFeelException exc ) {
                exc.printStackTrace();
            } catch ( ClassNotFoundException exc ) {
                exc.printStackTrace();
            } catch ( InstantiationException exc ) {
                exc.printStackTrace();
            } catch ( IllegalAccessException exc ) {
                exc.printStackTrace();
            }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransformar;
    private javax.swing.JComboBox<String> cbTipoCriatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCar;
    private javax.swing.JLabel labelCarPericia;
    private javax.swing.JLabel labelCon;
    private javax.swing.JLabel labelConPericia;
    private javax.swing.JLabel labelDados;
    private javax.swing.JLabel labelDes;
    private javax.swing.JLabel labelDesPericia;
    private javax.swing.JLabel labelFor;
    private javax.swing.JLabel labelForPericia;
    private javax.swing.JLabel labelForca;
    private javax.swing.JLabel labelInt;
    private javax.swing.JLabel labelIntPericia;
    private javax.swing.JLabel labelLegenda;
    private javax.swing.JLabel labelMais;
    private javax.swing.JLabel labelNivel;
    private javax.swing.JLabel labelPMs;
    private javax.swing.JLabel labelSab;
    private javax.swing.JLabel labelSabPericia;
    private javax.swing.JLabel labelVidaTotal;
    private javax.swing.JLabel lblModCar;
    private javax.swing.JLabel lblModCon;
    private javax.swing.JLabel lblModDes;
    private javax.swing.JLabel lblModFor;
    private javax.swing.JLabel lblModInt;
    private javax.swing.JLabel lblModSab;
    private javax.swing.JPanel painelAtributos;
    private javax.swing.JPanel painelCaracteristicas;
    private javax.swing.JPanel painelModificadores;
    private javax.swing.JPanel painelNome;
    private javax.swing.JPanel painelNomes;
    private javax.swing.JPanel painelPv;
    private javax.swing.JPanel painelTipoNivel;
    private javax.swing.JPanel painelValores;
    private javax.swing.JTextField txtCar;
    private javax.swing.JTextField txtCon;
    private javax.swing.JTextField txtDados;
    private javax.swing.JTextField txtDes;
    private javax.swing.JTextField txtFor;
    private javax.swing.JTextField txtInt;
    private javax.swing.JTextField txtModVida;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSab;
    // End of variables declaration//GEN-END:variables
}
